/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 24 13:32:17 GMT 2018
 */

package main.java.net.mooctest;

import org.junit.Test;
import static org.junit.Assert.*;
import main.java.net.mooctest.Month;
import main.java.net.mooctest.Year;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CalendarUnit_ESTest extends CalendarUnit_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Year year0 = new Year(6);
      year0.setCurrentPos(0);
      int int0 = year0.getCurrentPos();
      assertTrue(year0.isLeap());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Year year0 = new Year(8);
      Month month0 = new Month(8, year0);
      int int0 = month0.getCurrentPos();
      assertEquals(8, int0);
      assertEquals(8, year0.getYear());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Year year0 = new Year((-698));
      int int0 = year0.getCurrentPos();
      assertEquals((-698), int0);
  }
}
